### ISSUE TITLE
Factory with magic method

### ISSUE THREAD

**Issue by hrach** [nette/di#103]
Currently, it is not possible to define service factory as call of magic method. It throws `Factory 'Aws\Sdk::createSqs' used in service '237' is not callable.` It's because this checks https://github.com/nette/di/blob/514991b0b06dd6ba2c63d86f207f9d91cfacf05e/src/DI/ContainerBuilder.php#L473-L484 throws `ReflectionException: Method Aws\Sdk::createSqs() does not exist`. See Sdk [class definition](https://github.com/aws/aws-sdk-php/blob/f8c0cc9357e10896a5c57104f2c79d1b727d97d0/src/Sdk.php#L119).

I would like to create client services for particular AWS services. It's much cleaner to inject client directly, than injecting Sdk and then creating a client in the class.

``` neon
services:
    - Aws\Sdk({
        credentials: {
            key: %aws.access%,
            secret: %aws.secret%,
        },
        version: latest,
        region: 'eu-west-1',
    })
    -
        class: Aws\Sqs\SqsClient
        factory: @Aws\Sdk::createSqs
```

**Comment by enumag** [comment]
If I'm reading the class correctly, this should work:

```
    -
        class: Aws\Sqs\SqsClient
        factory: @Aws\Sdk::createClient('sqs')
```

**Comment by hrach** [comment]
Yeah, also `@Aws\Sdk::__call('createSqs')` works.
