### ISSUE TITLE
BC Break in ServiceDefinition (SmartObject)

### ISSUE THREAD

**Issue by fprochazka** [nette/di#107]
Introduced in https://github.com/nette/di/commit/69b056e9ad012598187e7f19f12104aab64dacbe, related https://github.com/nette/di/pull/106

[It](https://github.com/Kdyby/DoctrineCache/commit/6676794f80d9b2f8784a2b76078c64c65a1e46a0) [would](https://github.com/Kdyby/Doctrine/commit/3e8bd5deb6c5aab514c62c228a14fb86f9846ce1) [be](https://github.com/Kdyby/Console/commit/0a1472c2f6ae1c278b5c8592ff8264660718679a) [nice](https://github.com/Kdyby/Events/commit/896f1a0679f4ecd7141ce4b09502002fb2704543) [if](https://github.com/Kdyby/Monolog/commit/7510988e1f9b421760451836d80e95ca00cd4588) [somebody](https://github.com/Kdyby/Translation/commit/b0517f926ea1217ed069a8fe6d70f1004e37b0d6) [could](https://github.com/Kdyby/Annotations/commit/cdbc0e4beb6473eb00043790a104230c0c8f0bca) [fix](https://github.com/Kdyby/Validator/pull/24/commits/3898773850ff8b9cc2539e474473d49b487b9393) this BC break - since this is pretty hard deprecation (while there is no reason for it) and it would be nice to have some transition time with soft-deprecation.
Yaay for removing magic, booo for BC Breaks :)

I may do it myself, but I would preffer if somebody else did it - since I have very little free time right now
Thanks.

**Comment by dg** [comment]
You haven't time to add 5 `@property` annotations?

**Comment by fprochazka** [comment]
@dg It's almost never "just a few properties" as @enumag learned few hours ago.

It's also a good idea to check if what you're doing actually makes sense and if you haven't forgotten anything. Few lines can easily become hours of work.

**Comment by fprochazka** [comment]
@dg thanks for fixing it.

**Comment by dg** [comment]
Ok, it was 6 properties https://github.com/nette/di/commit/5e32205f76d1455f57c9fda4f3d1a0090e4ac1ed & https://github.com/nette/php-generator/commit/bf60eaad18cd1a2ab372cc9637a509c38daa4252
