### ISSUE TITLE
Unreliable setup ServiceDefinition of generated factory

### ISSUE THREAD

**Issue by JanTvrdik** [nette/di#118]
The following code may or or may not work at all depending on whether the service implementation is generated by Nette DI.

``` php
$serviceName = $builder->getByType(Nette\Bridges\ApplicationLatte\ILatteFactory::class);
$serviceDef = $builder->getDefinition($serviceName);

// this may configure either ILatteFactory or Latte\Engine instance
$serviceDef->addSetup('addFilter', ...);
```

I think that the current behavior is highly confusing. Service definition of the implementation should use different instance (e.g. `$serviceDef->getInstanceDef()->addSetup('addFilter', ...)`).

When the factory implementation is not generated by Nette DI, modifying of the definition of instance service definition should ideally generate another implementation which would wrap the user provided implementation.

cc @matej21

**Comment by dg** [comment]
In v3.0 this should work as expected.

```php
$serviceDef->getResultDefinition()->addSetup('addFilter', ...)
```
