### ISSUE TITLE
DependencyChecker tries to load a class that should not be loaded

### ISSUE THREAD

**Issue by enumag** [nette/di#124]
It's probably best to show this on the real case:

- `Kdyby\Events\EventsManager::setPanel()` needs argument of `Kdyby\Events\Diagnostics\Panel`
- `Kdyby\Events\Diagnostics\Panel` implements `Tracy\IBarPanel`
- kdyby/events has tracy/tracy as an optional dependency
- => `Tracy\IBarPanel` may not exist
- but that does not matter because `Kdyby\Events\Diagnostics\Panel` is never loaded at all

The problem is that DependencyChecker is still trying to load the `Kdyby\Events\Diagnostics\Panel` class:
- `DependencyChecker::calculateHash()` [iterates](https://github.com/nette/di/blob/6f645e613683f141cab2cd48bbd6484cd2d233a9/src/DI/DependencyChecker.php#L105) over all public methods of `Kdyby\Events\EventsManager` which of course includes the `setPanel` method
- `calculateHash` [calls](https://github.com/nette/di/blob/6f645e613683f141cab2cd48bbd6484cd2d233a9/src/DI/DependencyChecker.php#L111) `DependencyChecker::hashParameters()` which iterates over all parameters of the `setPanel()` method (which is only the panel parameters).
- `hashParameters` [calls](https://github.com/nette/di/blob/6f645e613683f141cab2cd48bbd6484cd2d233a9/src/DI/DependencyChecker.php#L148) `PhpReflection::getParameterType($param)`
- `getParameterType` [calls](https://github.com/nette/di/blob/6f645e613683f141cab2cd48bbd6484cd2d233a9/src/DI/PhpReflection.php#L66)) `$param->getClass()`
- that will try to autoload the `Kdyby\Events\Diagnostics\Panel` class
- which of course fail with `Fatal error: Interface 'Tracy\IBarPanel' not found`
- (no ReflectionException to catch, just fatal error)

**Comment by dg** [comment]
Seems like PHP 5 bug, can you report it?

**Comment by enumag** [comment]
I don't think it's a PHP bug... ReflectionClass autoloads the class in question, composer finds the file where the class is and includes it, PHP throws Fatal error because it is unable to execute the file because of the missing interface. Which part is buggy in your opinion? I think all of it is normal.

**Comment by enumag** [comment]
@dg That was fast! Thank you. :+1:

**Comment by enumag** [comment]
Ok, maybe it is a PHP bug. My build on Travis failed on PHP 5.6 but passed on 5.5, 7.0 and 7.1.
