### ISSUE TITLE
Add getDefinitionByType() method

### ISSUE THREAD

**Issue by TomasVotruba** [nette/di#130]
While making extension, I often need some **service definition** in `beforeCompile()` method, e.g.:

- [load all Commands to Symfony Console Application](https://github.com/Zenify/DoctrineMigrations/blob/e82c11f8047dad44dbf16edf31afec5da636e462/src/DI/MigrationsExtension.php#L115-L122)
- [load all Fixtures to Alice](https://github.com/Zenify/DoctrineFixtures/blob/cc937219900a34ee48ee50bae08af3093ab9f06b/src/DI/FixturesExtension.php#L66-L69)
- [load all SqlFilters to Doctrine Filter Manager](https://github.com/Zenify/DoctrineFilters/blob/0c768dc78ba9e0b1c491da3170f3f1a4589d1989/src/DI/FiltersExtension.php#L42-L51)
- [load Filter Providers to Latte Engine](https://github.com/Zenify/ModularLatteFilters/blob/501b940a2a764aacebe5c781111434806e79cc3e/src/DI/ModularLatteFiltersExtension.php#L34-L41)

After making service name optional, this is the only place where it is still required.

Everywhere I need some definition, I have to use these 2 methods:

```php
$containerBuilder = $this->getContainerBuilder();
$serviceName = $containerBuilder->getByType(Nette\Bridges\ApplicationLatte\ILatteFactory::class);
$serviceDefinition = $containerBuilder->getDefinition($serviceName);
```

I would prefer having single method:

```php
$serviceDefinition = $containerBuilder->getDefinitionByType(
    Nette\Bridges\ApplicationLatte\ILatteFactory::class
);
```

What do you think?

**Comment by dg** [comment]
:+1:
