### ISSUE TITLE
why di config/loader parsed result is not compatible to neon format?

### ISSUE THREAD

**Issue by andares** [nette/di#134]
I am improved the config class with neon, now it can be write like this:

```
services:
    - App\Play\Provider
    - App\Play\Sender
    - App\Play\Logger(dev.log)

prod < services:
    - App\Play\Logger(prod.log)

test < services:
    - App\Play\Logger(test.log)
```

it can merge config in every env, I'd like it :-P

but when I try to use addConfig() method to set di config to compiler, it was error, because ```Nette\Neon\Entity``` is not ```Nette\DI\Statement```

could you make they to be same class? or compatible neon entity in Validator?

**Comment by dg** [comment]
Can you show you code?

**Comment by andares** [comment]
look, by the sample I can make di like this:

```
$class = $loader->load(function($compiler) {
    $config = combi()->app->path('src', 'config/services.neon');
    $compiler->loadConfig($path);
});
```

it's no problem.

now, I want to do something before config load, and I still use neon format. so I couldn't use ```loadConfig()``` method, so I try to load and parse neon config by myself, and use ```addConfig()``` method to put config into compiler.

```
$class = $loader->load(function($compiler) {
    $config = combi()->app->config('services')->toArray(); // it return array like Neon::decode().
    $compiler->addConfig($config);
});
```

and will throw exception:

```
<b>Fatal error</b>:  Uncaught Nette\Utils\AssertionException: The item 'factory' in array expects to be callable or Nette\DI\Statement or null, object Nette\Neon\Entity given. in /home/andares/repos/combi/combi/vendor/nette/utils/src/Utils/Validators.php:90
```

because neon::decode() will return entity object, di system need di\statement, although they look very similar. I think it should be more compatible.

var_dump for my parsed config:

```
array(1) {
  ["services"]=>
  array(3) {
    [0]=>
    string(17) "App\Play\Provider"
    [1]=>
    string(15) "App\Play\Sender"
    [2]=>
    object(Nette\Neon\Entity)#11 (2) {
      ["value"]=>
      string(15) "App\Play\Logger"
      ["attributes"]=>
      array(1) {
        [0]=>
        string(7) "dev.log"
      }
    }
  }
}
```

=============================

you can see my config class in the links:

https://github.com/andares/combi-core/blob/master/src/classes/Core/Config.php
https://github.com/andares/combi-core/blob/master/tests/classes/Core/Config.php

It is bind to neon libs, I can add some code to trans neon\entity to di\statement, but it is low efficiency.

I will try to add neon\entity support to di libs tomorrow.

**Comment by dg** [comment]
`$compiler->addConfig()` accepts array, so it is (intentionally) independent from the source format, so it doesn't understand `Nette\Neon\Entity`. Conversion Entity -> Statement is done by Nette\DI\Config\Adapters\NeonAdapter::process(). I have changed visibility to public, so you can use now:

```php
$compiler->addConfig((new Nette\DI\Config\Adapters\NeonAdapter)->process($config));
```

**Comment by andares** [comment]
got it, thank you very much!
