### ISSUE TITLE
ContainerBuilder - Collector feature, Modular<Filters|Routes>, Commands, EventSubscribers...

### ISSUE THREAD

**Issue by TomasVotruba** [nette/di#139]
- bug report? no
- feature request? yes

This should make `CompilerExtension` more usable.

### Examples of current usage in Extension

This is how it's done now. Bellow is suggestion how to do it better.

- load all console Commands to Application - [Kdyby\Console](https://github.com/Kdyby/Console/blob/b6ab544a125aff4880fad82fe19736302d4959a6/src/Kdyby/Console/DI/ConsoleExtension.php#L163-L166)
- load all Doctrine SqlFilter to FilterManager - [Kdyby\Events](https://github.com/Kdyby/Events/blob/81716e12fa8dc5136fbd7c5071134ca401a4bda9/src/Kdyby/Events/DI/EventsExtension.php#L133-L136)
- load all Modular SqlFilters to Doctrine - [Zenify\DoctrineFilters](https://github.com/Zenify/DoctrineFilters/blob/a3a1240cb16acb372fc7beddf9ac7ad4793e7ddd/src/DI/FiltersExtension.php#L44-L51)
- add some Generators to Queue - [Apigen\Apigen](https://github.com/ApiGen/ApiGen/blob/ffd28665896730d330f3003ec0cd7c1cb1d7a31a/src/DI/ApiGenExtension.php#L66-L72)
- load all Modular Filters to Latte - [Zenify\ModularLatteFilters](https://github.com/Zenify/ModularLatteFilters/blob/aba4d54aa5e78e4ce125cad016246aa2d3eb88f6/src/DI/ModularLatteFiltersExtension.php#L34-L42)

### Issue: add services that implement certain interface to one collecting service

Current solution is by tag, which has few disadvantages:

- **bothers user to remember the tag**, even the class is already specific (by interface it implements or class it extends)
- **polutes config**

```yaml
services:
    - 
        class: SomeCommand
        tags: "console.command"
```

instead of

```yaml
services:
    - SomeCommand
```

- has origin in times of named services when duplicated info, context and service locator, was normal to use
 

### Better solution

Based on new `getDefinitionByType()` method (https://github.com/nette/di/pull/137) and `findByType()` I suggest adding following method to `ContainerBuilder` class:

(Feel free to improve the naming.)

```php
public function setToCollectorByType(string $collectorClass, string $collectedClass, string $setterMethod) : void
{
    $containerBuilder = $this->getContainerBuilder();

    $collectorDefinition = $containerBuilder->getDefinitionByType($mediatorClass);
    $collectedDefinitions = $containerBuilder->findByType($collectedClass)    

    foreach ($collectedDefinition as $name => $definition) {
        $collectorDefinition->addSetup($setterMethod, ['@' . $name]);
    }
}
```

### Before

```php
use Nette\DI\CompilerExtension;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;

class MyExtension extends CompilerExtension
{
    public function beforeCompile()
    {
        $containerBuilder = $this->getContainerBuilder();
    
        $consoleApplication = $containerBuilder->getDefinitionByType(Application::class);
        foreach ($containerBuilder->findByType(Command::class) as $name => $definition) {
            $consoleApplication->addSetup('add', ['@' . $name]);
        }
}
```

### After

```php
use Nette\DI\CompilerExtension;
use Symfony\Component\Console\Application;
use Symfony\Component\Console\Command\Command;

class MyExtension extends CompilerExtension
{
    public function beforeCompile()
    {
        $this->setToCollectorByType(Application::class, Command::class, 'set);
    }
}
```

This would simplify so many use cases and encourage this architecture pattern.

What do you think?

**Comment by JanTvrdik** [comment]
I don't think I understand the problem. Can't you already use decorator to add tags automatically?

**Comment by TomasVotruba** [comment]
This is related to `CompilerExtension` mainly, see all examples. I've added this note above.
See examples in extensions. That's the use case to improve.

**Comment by JanTvrdik** [comment]
> I mean where do you need to collect only few of services of certain type (e.g. few Commands) and not all?

e.g. you want to have two Symfony Application instances with different set of commands.

**Comment by TomasVotruba** [comment]
> e.g. you want to have two Symfony Console Application instances with different set of commands.

Yea, that's not the use case this solves.

I've updated the description with before/after.

**Comment by dg** [comment]
I really see no advantage in replacing these two lines of readable (and only a little used) code 

```php
foreach ($builder->findByType(Command::class) as $definition) {
            $service->addSetup('add', [$definition]);
}
```

with 

```php
$this->setToCollectorByType(Application::class, Command::class, 'set'); // rather it would be more appropriate $this->setToCollectorByType($service, Command::class, 'set'); 
```

**Comment by TomasVotruba** [comment]
@dg Thanks for specific code examples. I'll think about your points and try them in practice.

I find this feature useful to embrace decoupling and creating modular system.

**Comment by TomasVotruba** [comment]
Closing for now as not so relevant for framework integration.

Here is helper I created for simpler API in my apps:

https://github.com/Symplify/Symplify/blob/434a8fd4e60fa9ff37befbde8f80b1763b2c878c/packages/PackageBuilder/src/Adapter/Nette/DI/DefinitionCollector.php#L9
