### ISSUE TITLE
Unable to resolve constant Doctrine\ORM\Mapping\CASE_LOWER

### ISSUE THREAD

**Issue by TomasVotruba** [nette/di#140]
- bug report? yes
- feature request? no
- version: 2.4.6

Not sure where to report this, because more packages were released today.

After those releases, system class constant stopped working.

See: https://github.com/doctrine/doctrine2/pull/6234#issuecomment-272724429

**Comment by dg** [comment]
Maybe this is fix https://github.com/nette/utils/commit/f2cc01d9762a8215f9fdca3344eaba184e93c339

**Comment by aleswita** [comment]
@dg after update "nette/utils" to "~2.4.0-dev" works fine

**Comment by juniwalk** [comment]
@dg Yep it works.
