### ISSUE TITLE
Possibility to register core DIC extension before other extensions

### ISSUE THREAD

**Issue by mrtnzlml** [nette/di#143]
- bug report? **no**
- feature request? **yes**
- version: **3.0.0** 

### Description
In `v3.0.0-alpha1` there is final class `ExtensionsExtension` which is huge BC break for extensions replacing `ExtensionsExtension`. This cannot be easy workarounded. I tried to solve this issue in PR https://github.com/nette/di/pull/142 but I understand that it's just another workaround and proper solution is needed.

@dg talked about prioritization of DIC extensions. I don't have idea what are the plans here but this should be (I wish) solved **before stable release** otherwise it's not possible to upgade uprojects with custom `ExtensionsExtension`.

Example of extension relying on this feature: [adeira/compiler-extension](https://github.com/adeira/compiler-extension)

Thank you very much.

**Comment by TomasVotruba** [comment]
Just wondering, how to solve a concurrency? 

- What happens when 2 packages will try to register the same extension?
- When happens, when one extension is already registered manually and another will be registered via this extension.

**Comment by mrtnzlml** [comment]
> What happens when 2 packages will try to register the same extension?

You can do it even with current DI ([test](https://github.com/nette/di/blob/7113e45bcff7caa6daeae8221d3578b35579836d/tests/DI/Compiler.extension.anonymous.phpt)). From my point of view this is your problem, not DI.

> When happens, when one extension is already registered manually and another will be registered via this extension.

This doesn't make sense. It's the same situation. But usually there is only one `ExtensionsExtension` (overriden) so this is not an issue. See [adeira/compiler-extension](https://github.com/adeira/compiler-extension) for more details how to use it properly if you are interested.

**Comment by TomasVotruba** [comment]
I understand that it works, when used properly by one person.

But let's say you create a package, that you registers Kdyby\Doctrine extension.
And I will do the same in my package (without knowing you did, of course).

There will be 2 extension of one type? Just wondering, what conflicts that could lead to.

**Comment by mrtnzlml** [comment]
Thankfully it's not possible to manipulate extensions in config provided via method `provideConfig` (talking about *adeira/compiler-extension*). It needs just a little improvement because it doesn't throw exception (it's already on "to do" list).

I can imagine to add this feature, because it's not complicated to check if that extension is already registered but at this moment it's not designed for this use case. I never needed this behavior but it opens new way of package isolation...

**Comment by TomasVotruba** [comment]
I see. Thanks for sharing your know-how around this topic.

**Comment by mabar** [comment]
What about creating method which returns with which providers is extension working? This way can be extensions priorities build without configuration.

- Get providers from all extensions (eg. Kdyby/Translation extension works with Kdyby\Translation\DI\ITranslationProvider)
- Get extension which implements these providers
- Build a tree of dependencies
- Finally process extensions in correct order.

**Comment by mabar** [comment]
One more idea - is it possible to first load the list of all extensions than start working with them?
Extension would be not able to work with others in __construct, but in other methods would be available all of them everytime. Simple and not BC break.
```php
foreach ($this->compiler->getExtensions() as $extension) {}
```
This code would get all extensions no matter of their order. Or is there another way you are working with extensions?

**Comment by dg** [comment]
Maybe future is in something like this:

```php
final class NewTypeOfExtension extends Nette\DI\CompilerExtension
{

	public function initialize()
	{
		$compiler = $this->getCompiner();
		$compiler->registerMethod([$this, 'addExtensions'], $compiler::WILL_ADD_EXTENSIONS);
		$compiler->registerMethod([$this, 'addDefinitions'], $compiler::WILL_ADD_SERVICES);
		$compiler->registerMethod([$this, 'updateXyz'], $compiler::WILL_MODIFIY_SERVICES | $compiler::WILL_READ_TAGS);
		$compiler->registerMethod([$this, 'updateKlm'], $compiler::WILL_WRITE_TAGS | $compiler::WILL_READ_TAGS);
	}

	function addDefinitions()
	{
		// ...
```

And then build tree of dependencies.
