### ISSUE TITLE
Changed service causes dependency checks on every request

### ISSUE THREAD

**Issue by fmasa** [nette/di#144]
There is a problem with current DIC expiration check.

Cosider following config:
```yaml
services:
- MyService
```

Let's say I change content of MyService.php from
```php
<?php
class MyService {}
```
to
```php
<?php
class MyService
{
    public function foo();
}
```
*(file changed, dependencies didn't)*

On next request `DependencyChecker` compares modification times with meta file of generated container, which differs. Dependency hash is now calculated and matches the one in meta file, so container is considered non-expired.

The problem is that meta file is not updated and hash is calculated on every request, which leads to performance overhead for large containers.

**Comment by TomasVotruba** [comment]
Hi, could you send simple failing test please?

**Comment by TomasVotruba** [comment]
Thank you @dg !

**Comment by fmasa** [comment]
Thanks :) @dg
