### ISSUE TITLE
DecoratorExtension does not support traits

### ISSUE THREAD

**Issue by h4kuna** [nette/di#161]
- bug report? no
- feature request? yes

### Description
Hi,
if i have trait which has setter or whatever i can't use decorator. I see php function **is_a** does not support it. Do you think is a good idea?

I use like this now, where is static function **isA()** and extended condition in function **findByType**.

I can prepare PR.

### Steps To Reproduce
```php
<?php

namespace App\Extensions;

use Nette;

class DecoratorTraitExtension extends Nette\DI\Extensions\DecoratorExtension
{
	public function addSetups($type, array $setups)
	{
		foreach ($this->findByType($type) as $def) {
			foreach ($setups as $setup) {
				if (is_array($setup)) {
					$setup = new Nette\DI\Statement(key($setup), array_values($setup));
				}
				$def->addSetup($setup);
			}
		}
	}


	private function findByType($type)
	{
		return array_filter($this->getContainerBuilder()->getDefinitions(), function ($def) use ($type) {
			return is_a($def->getType(), $type, TRUE) || is_a($def->getImplement(), $type, TRUE) || self::isA($def->getType(), $type);
		});
	}


	private static function isA($className, $traitName)
	{
		try {
			$traitReflection = new \ReflectionClass($traitName);
		} catch (\ReflectionException $e) {
			throw new Nette\InvalidArgumentException('Trait does not exists: ' . $traitName);
		}

		if (!$traitReflection->isTrait()) {
			return FALSE;
		}

		return self::hasTrait(new \ReflectionClass($className), $traitName);
	}


	private static function hasTrait(\ReflectionClass $class, $traitName)
	{
		$traits = $class->getTraits();
		if (isset($traits[$traitName])) {
			return TRUE;
		}

		foreach ($traits as $traitReflection) {
			if (self::hasTrait($traitReflection, $traitName)) {
				return TRUE;
			}
		}

		if ($class->getParentClass()) {
			return self::hasTrait($class->getParentClass(), $traitName);
		}
		return FALSE;
	}
}
```

**Comment by enumag** [comment]
You should use an interface + trait in such cases. Just a trait is not a good idea in my opinion.

**Comment by h4kuna** [comment]
Here is easy example. Where two classes have different parent but both have trait. And interface is not posibble.

Defined in neon
```neon
extensions:
	decoratorTrait: AppInt\Config\DecoratorTraitExtension

decoratorTrait:
	App\TItemCache:
		setup:
			- setStorage(@apcuStorage)
```
Trait has any implementation
```php
namespace App;
use Nette\Caching;
trait TItemCache
{

	/** @var Caching\IStorage */
	private $storage;

	/** @var Caching\Cache */
	private $cache;

	public function setStorage(Caching\IStorage $storage)
	{
		$this->storage = $storage;
	}


	/** @return Caching\Cache */
	public function getCache()
	{
		if ($this->cache === NULL) {
			$this->cache = new Caching\Cache($this->storage, get_class($this));
		}
		return $this->cache;
	}

}
```
Use case:
```php
class Bar {
    public function __contruct(A $a, B $b, C $c, D $d) {
      ...
    }

}

class Foo extends Bar {
    use \App\TItemCache;
}

class Doe extends Bar {
}

class Joe extends Xyz {
    use \App\TItemCache;
}
```

**Comment by enumag** [comment]
The "With interface + trait" section is what I meant and what I would use. Is there some problem with that?

**Comment by h4kuna** [comment]
For this moment, no. But why is it problem when trait support independently? I wrote only for preview by your previous answer.

There are two conditions for implementation interface and trait for every class.

**Comment by f3l1x** [comment]
I like traits for their simplicity, but also I consider them as "usage sugar". My protip is: *You should not relay on them.*. 

For example:

```
interface IContainerAware
{
	/**
	 * @param Container $container
	 */
	public function setContainer(Container $container);
}
``` 

```
	public function beforeCompile()
	{
		$builder = $this->getContainerBuilder();
		foreach ($builder->findByType(IContainerAware::class) as $service) {
			$service->addSetup('setContainer');
		}
	}
```

**Comment by enumag** [comment]
Basically trait should not be used to indicate that the class supports something (such as having a callback for caching or whatever it is you're trying to do). That's what interfaces are for. If the implementation happens to be usually the same you can use trait to simplify your code. But you should not think of the trait as a replacement for the interface.

**Comment by milo** [comment]
@h4kuna Interface ensures that class has such method name and signature. And other code can trust it. Trait cannot ensure it. Consider:
```php
trait T
{
    public function foo() {}
}

class C
{
    use T:foo as bar;
}
```
so the class `C` does not contain method `foo()` but contains `bar()`.

**Comment by h4kuna** [comment]
@milo You have right, i did'nt realize to use trait can rename method.
