### ISSUE TITLE
Recursive includes

### ISSUE THREAD

**Issue by Trejjam** [nette/di#162]
- bug report? yes
- feature request? yes
- version: 2.4.10

### Description
Recursive config `includes` end with environment timeout or memory exhausted.

### Steps To Reproduce
```php
$configurator = new Nette\Configurator;
$configurator->setTempDirectory(__DIR__ . DIRECTORY_SEPARATOR . 'temp');
$configurator->addConfig('config.neon');
$configurator->createContainer();
```

config.neon:
```yml
includes:
  - config.neon
```

It is basically bug in .config files, but I thinks that could be handled into exception?

**Comment by dg** [comment]
Can you fix it and send PR?

**Comment by Trejjam** [comment]
Yes
