### ISSUE TITLE
Extending of NeonAdapter in v3

### ISSUE THREAD

**Issue by o5** [nette/di#193]
I would like to use version 3, but [this change](https://github.com/nette/di/commit/661c19e483ed592e2e8814a336c23c5203ab3858) is a problem for me :) I am using a custom `NeonAdapter` with overloading of one method `load()`, it looks like this:

```php
public function load($file): array
{
    return $this->process((array) Neon::decode((string) shell_exec("envsubst < $file")));
}
```

The [envsubst](https://www.gnu.org/software/gettext/manual/html_node/envsubst-Invocation.html) is useful when you want to replace ENV values in your NEON files which is the simplest way for application secrets in continuous delivery.

Now, I have to copy&paste the whole implementation for this one-liner change. Or should I fork this repo and remove `final`? 

I know the date of referenced commit and also date of the first alpha release but I missing the reason why `final` keyword is used there.

**Comment by mabar** [comment]
https://www.php.net/manual/en/wrappers.php.php
https://code.tutsplus.com/tutorials/design-patterns-the-decorator-pattern--cms-22641

**Comment by JanTvrdik** [comment]
@o5 You should you decoration instead of inheritance.

**Comment by dg** [comment]
This way:

```php
final class MyNeonAdapter implements Nette\DI\Config\Adapter
{
	public function load(string $file): array
	{
		return (new NeonAdapter)->process((array) Neon::decode((string) shell_exec("envsubst < $file")));
	}

	public function dump(array $data): string
	{
		return (new NeonAdapter)->dump($data);
	}
}
```
