### ISSUE TITLE
Bad compilation of schemas

### ISSUE THREAD

**Issue by tomat364** [nette/di#194]
Version: 3.0

### Bug Description
I have created in the neon file statically roles
```
security:
    roles:
        guest:
        member: [guest]
        admin:
```
compiler requires you to specify a parent parameter that can be null
```
    * @param  string|array $parents
     * @throws Nette\InvalidArgumentException
     * @throws Nette\InvalidStateException
     * @return static
     */
    public function addRole(string $role, $parents = null)
```
<img width="715" alt="Snímek obrazovky 2019-04-12 v 7 29 01" src="https://user-images.githubusercontent.com/13833953/56032284-14c16280-5d22-11e9-9e80-d2c735eaa8bb.png">

the same applies to entering an empty field
```
security:
    roles:
        guest: []
```
the result is an error `The option 'security › roles › guest' expects to be string, array given`

I published the problem on slack and Milo referred me to the issue of issue to fine-tune the scheme.

**Comment by PavelJurasek** [comment]
Maybe this one:
```
security:
    roles:
        - guest
```

**Comment by tomat364** [comment]
Record:
```
security:
	roles:
		- guest
		- member
		- admin
```
creates such a record
```
$service = new Nette\Security\Permission;
$service->addRole(0, 'guest');
$service->addRole(1, 'member');
$service->addRole(2, 'admin');
```

**Comment by tomat364** [comment]
Problem is here:
`SecurityExtension.php:44`

```
'roles' => Expect::anyOf(Expect::array('array'), Expect::null('null')), // role => parent(s)

```
I adjusted to
```
'roles' => Expect::anyOf(Expect::array('array'), Expect::null('null')), // role => parent(s)
```
and it's ok
