### ISSUE TITLE
Compiler Extension config defaults

### ISSUE THREAD

**Issue by vojtamares** [nette/di#202]
Hello,

to be honest I am not sure if this should be feature request of bug report.

In `nette/di:3.0.0` function [`Nette\DI\CompilerExtension::validateConfig()`](https://github.com/nette/di/blob/master/src/DI/CompilerExtension.php#L83) was deprecated and replaced by [`Nette\DI\CompilerExtension::getConfigSchema()`](https://github.com/nette/di/blob/master/src/DI/CompilerExtension.php#L70)

But since this change, I do not see an easy way to use default values if no other are provided by user. 

I think that this should be handled by `Nette\DI\CompilerExtension` class and provide unified API for all extensions and not be handled by every extension on it's own which may lead to inconsistency across extensions' configuration.

I purpose to add a function such as `addConfigDefaults()` which would set config values, but would not override existing ones.

I am currently facing this issue when upgrading [contributte/elasticsearch (PR)](https://github.com/contributte/elasticsearch/pull/7) to Nette 3

**Comment by mabar** [comment]
`Expect::string($default)` or `Expect::string()->default($default)`

**Comment by vojtamares** [comment]
Solved with `Nette\DI\CompilerExtension::getConfigSchema()`

Example:
```php
use Nette\DI\CompilerExtension;
use Nette\Schema\Expect;
use Nette\Schema\Schema;

class MyExtension extends CompilerExtension
{

    private $defaults = [
        'value' => ['otherValue']
    ];

    public function getConfigSchema(): Schema
    {
        return Expect::structure([
            'value' => Expect::array()->default($this->defaults['value']) // [ 'value' => ['otherValue'] ]
        ]);
    }

}
```

Closed.
