### ISSUE TITLE
Request for minor patch back to 2.4 (container not calling parent constructor)

### ISSUE THREAD

**Issue by slepic** [nette/di#205]
Version: latest 2.4

Hi,
I have a little request to merge a fix that exists in 3.0 branch back to 2.4 branch.
It is problem with generated containers not calling parent constructor. You probably know what it refers to so I wont go any deeper...
It's a matter of one or two lines change, or maybe can even be cherry-picked from some forthcoming commit, I havent investigated in that respect yet.
First I wanted to ask If you'd be willing for such a fix in an old version, so that I dont waste time doing something thats not gonna get merged.
Let me explain why I need this. I have recently introduced phpstan in my job project and I want to make it part of our travis build to check whether everything is ok. Problem is this missing call to parent constructor is making the phpstan analysis fail and so I cannot automate it, I can only run it manualy and check that there is only that one error. Well I could write a script for this scenario to turn error into success but I'd rather not go that way...
I have removed all other errors, but I am unable to remove this one. I cannot upgrade to nette 3.0 yet (since we use packages depending on nette that dont have 3.0 compatible versions yet). And I cannot find out a workaround for this.

So, would you merge this back to 2.4 for me please? I'll provide a PR, thats no problem...

**Comment by dg** [comment]
The problem is that there will be no more release of 2.4.x (except that there is a serious security bug, which is certainly not the case of nette/di package). 

Possible way how to fix it is to create CompilerExtension and modify __construct in afterCompile.

**Comment by slepic** [comment]
Awesome tip. That will do it.

Díky moc :)
