### ISSUE TITLE
InjectExtension not work when set factory and type 

### ISSUE THREAD

**Issue by MartkCz** [nette/di#218]
Version: 3.0.1

```php
$definitions[$name] = $builder->addDefinition($this->prefix('controller.' . $name))
				->setType(IController::class)
				->addTag(InjectExtension::TAG_INJECT)
				->setFactory($controller);
```

InjectExtension search inject* methods in IController instead of `$controller` 

https://github.com/nette/di/blob/master/src/DI/Extensions/InjectExtension.php#L64

Is it bug or do I have to remove interface as type?

**Comment by PavelJurasek** [comment]
I guess you should use `addFactoryDefinition` and then `->getResultDefition()->setType(...)`.

**Comment by MartkCz** [comment]
Thanks,

but IController is not a factory, I guess `addFactoryDefinition` is only for create* methods that returns new object of specific type

IController:
```php
interface IController {

	public function start(IRequest $request, IClient $client): void;
	
}
```

**Comment by MartkCz** [comment]
Not working:

```yaml
factory: App\TestService
type: App\ITestService
inject: true
```

Working:
```yaml
factory: App\TestService
inject: true
```
