### ISSUE TITLE
Nette\DI\CompilerExtension::setConfig() must be of the type array issue in "nette/nette": "~2.3.10",

### ISSUE THREAD

**Issue by sahsuraj** [nette/di#223]
TypeError: Argument 1 passed to Nette\DI\CompilerExtension::setConfig() must be of the type array, string given, called in /home/maqtoobc/public_html/vendor/nette/di/src/DI/Compiler.php

**Comment by dg** [comment]
Nette 2.3 is not supported anymore, please update to newer version.

**Comment by sahsuraj** [comment]
If I upgrade to latest version then I need to update my code or not?

**Comment by sahsuraj** [comment]
how can i upgrade Nette 2.3 to latest? client website are https://maqtoob.com/

**Comment by sahsuraj** [comment]
how can i upgrade?

**Comment by PavelJurasek** [comment]
Update nette version in composer.json, run composer update and fix all the errors

**Comment by sahsuraj** [comment]
Hello guys , can you check this issue, website was working fine in php 5.6 but sudden get this issue

Recoverable Error: Argument 1 passed to Nette\DI\CompilerExtension::setConfig() must be of the type array, string given, called in /home/maqtoobc/public_html/vendor/nette/di/src/DI/Compiler.php on line 187
