### ISSUE TITLE
Broken enums as parameters

### ISSUE THREAD

**Issue by kukulich** [nette/di#227]
Version: 3.0.2

### Bug Description
We use enums as parameters in NEON configurations but it's broken in 3.0.2. Version 3.0.1 works well.

### Steps To Reproduce
Neon: 
```
	topCountries:
		- Slevomat\Country\Country::get(Slevomat\Country\Country::CODE_CZE)
```

It generates now:

```php
	'topCountries' => [
		Slevomat\Country\Country::get('Slevomat\Country\Country::CODE_CZE'),
	], 
```

### Expected Behavior
```php
	'topCountries' => [
		Nette\PhpGenerator\Dumper::createObject('Nette\DI\Definitions\Statement', [
			'arguments' => ['Slevomat\Country\Country::CODE_CZE'],
			"\x00Nette\\DI\\Definitions\\Statement\x00entity" => ['Slevomat\Country\Country', 'get'],
		]),
	],
```

**Comment by dg** [comment]
Probably related to #221

**Comment by dg** [comment]
I need to explain in more detail where the problem is.

**Comment by kukulich** [comment]
There are single quotes around `Slevomat\Country\Country::CODE_CZE` so the first parameter of `Slevomat\Country\Country::get()` is not `CZE` (the value of the constant) but the string `Slevomat\Country\Country::CODE_CZE`. I really don't what the previous code with `Dumper` does but it works :)

**Comment by dg** [comment]
In which part of the configuration is it?

**Comment by kukulich** [comment]
`parameters`

**Comment by dg** [comment]
What are you doing with parameter?

**Comment by kukulich** [comment]
1. Sometimes we use them as new parameters:

```
	otherParameter:
		- AnotherEnum::get(%topCountries%)
```

This is broken in 3.0.2.

```php
	'otherParameter' => [
		AnotherEnum::get([
			Slevomat\Country\Country::get('Slevomat\Country\Country::CODE_CZE'),
		]),
	],
```

2. We use them as arguments for services more often:

```
	-
		class: Slevomat\Api\NativeApplication\ProductList\Filter\CountryAndLocalityApiFilter
		arguments:
			topCountries: %topCountries%
```

This still works even with 3.0.2 version.

```php

	public function createService02100(): Slevomat\Api\NativeApplication\ProductList\Filter\CountryAndLocalityApiFilter
	{
		return new Slevomat\Api\NativeApplication\ProductList\Filter\CountryAndLocalityApiFilter(
			[Slevomat\Country\Country::get('CZ')]
		);
	}
```

**Comment by dg** [comment]
(Příště to prosím napiš hned, mě to doptávání dost štve)

**Comment by kukulich** [comment]
To nebylo schválně, ale spíš nedostatečnou znalostí, co by mohlo pomoct. Až moc dobře chápu, že doptávání není zábava.

**Comment by kukulich** [comment]
It works, thanks!
