### ISSUE TITLE
SearchExtension support names

### ISSUE THREAD

**Issue by dakujem** [nette/di#230]
Hello again.

## Overview of the idea

I stumbled upon `SearchExtension`, and it could replace an extension we use in our projects, but there is one critical feature missing: support for service names. This would prevent all auto-registered classes end up in one messy heap of classes as well as keep the auto-registered services in line with the structure of services already existing in the container.

Example use case is this: let's pretend we have the extension search for classes in app/repository and would like every class to be named according to a pattern, in this case `repository.*`. This way, `App\Repositories\FooRepo` would be registered as `repository.FooRepo`.

There should be 2 supported cases:
1. the name pattern is global for the section
2. the name pattern is specific to a class

To support case 1., a configuration option could be added, say `as`:
```neon
search:
	repositories:
		in: %appDir%/Repository
		as: repository.*
		classes:
			- App\*Repo
```

To support case 2., an annotation could be read from the class:
```php
/**
* Class FooRepo.
* @register-as repository.foo
*/
class FooRepo implements Repository { ... }
```
If a class had the annotation, it would take precedense over the configuration setting. It would also support wildcard, so `@register-as repository.*.default` would be also supported and would result in `repository.FooRepo.default` service name in this particular case.

Furthermore, there should be a way to configure how the substitution for the wildcard `*` is populated, the trivial case being the base class name, but it might be desirable to use either a specific algorithm or a specific string. For the string it could be another annotation `@register-name foobar`. Having the mentioned annotation would result in service name `repository.foobar`, in the example above. As to how to use an alogrythm, i'm not sure yet, but it might be desirable to use other parts of the namespace for example, in certain cases. Maybe we ould make the extension non-final to support user-specific cases for that or provide the option using adapter/visitor pattern.

## Changes

Calls to `$builder->addDefinition(null)` and `$builder->addFactoryDefinition(null)` would receive the name instead of `null`. Plus internal changes to how the class determins the service name and passes it along with tags from `loadConfiguration` to `beforeCompile` would of course be needed as well.

Since the class is final and the original functionality would be preserved, it would not be a BC break.

## Conclusion

Any ideas? Comments?\
I'm willing to provide a PR if these changes are desirable.

Otherwise it would be awesome to support extendibility without the need to copy the whole code by either turning `findClasses` into `public static` method along with making `buildNameRegexp` public as well, or making the whole extension non-final and non-private, so that inheritance would be possible.

**Comment by dg** [comment]
As the basic principle of IoC is that classes are completely DI container agnostic, point 2 cannot be used.

What is the use case? Why do you need to have a service named according to a pattern?

**Comment by dakujem** [comment]
First reason is purely aesthetic - looking at the list of services and having associated classes together gives pleasant feeling. 😄 

Second reason is functional. let's say we allow certain plug-in functionality just by adding classes to the DI under a certain prefix. I'm not saying this is optimal, but before you start about IoC, let me ensure you this happens at bootstrap level and the rest of the application does not know about it.

But I'm open to discarding the idea though, as I will probably be better off just using the extension I have used so far.

**Comment by dakujem** [comment]
Let me close this idea for apparent lack of interest with just one remark on the "completely DI container agnostic" point:\
I wonder whether the `@inject` annotation is also copletely DIC-agnostic.
