### ISSUE TITLE
Allow combination of splat operator and multiple services

### ISSUE THREAD

**Issue by survik1** [nette/di#241]
In case of dynamic service creation it would be nice to have possibility to inject all services trough splat operator.

`interface IService{}`
`class ServiceA implements IService {}`
`class ServiceB implements IService {}`

Autowiring both services and requiring DI to load IService will trigger Multiple services exception.
The following code should, however, be allowed

`__construct(IService ...$services) {}`

**Comment by dg** [comment]
I think that this is improper usage of splat operator, so I dont want to support it.

**Comment by dg** [comment]
Duplicate #244
