### ISSUE TITLE
Indirect access to variables, properties and methods will be evaluated strictly in left-to-right order since PHP 7.0

### ISSUE THREAD

**Issue by bkosborne** [nette/di#243]
Version: 3.0.5

### Bug Description
I ran a PHP compatibility scan on the codebase and it revealed the following:

"Indirect access to variables, properties and methods will be evaluated strictly in left-to-right order since PHP 7.0. Use curly braces to remove ambiguity."

when referring to line 147 in src/DI/Autowiring.php

See https://www.php.net/manual/en/migration70.incompatible.php for more information.

### Steps To Reproduce
N/A

### Expected Behavior
N/A

### Possible Solution
Add curly braces to this line to make it clearer what the intended order of execution is for this line:

`$this->$list[$parent][] = $name;`

**Comment by dg** [comment]
I think it is clear from context.
