### ISSUE TITLE
PHP 8: Call to undefined method ReflectionUnionType::getName()

### ISSUE THREAD

**Issue by dakujem** [nette/di#249]
Version: 3.0.5
PHP: 8.0 (RC3)

### Bug Description
`Call to undefined method ReflectionUnionType::getName()` in `DependencyChecker` line `151`.

A comment in php manual:
> Method `ReflectionType::getName()` does not exist. This may have been virtually true in the past but not anymore. It exists on ReflectionNamedType which used to be the only child class of ReflectionType. So you could have kind of relied on that.
>
> But in PHP 8 there's also ReflectionUnionType which doesn't have the getName() method. So in order to support PHP 8, you need to support both ReflectionNamedType and ReflectionUnionType.

https://www.php.net/manual/en/class.reflectiontype.php

**Comment by dg** [comment]
Duplicate #247
