### ISSUE TITLE
Allowing unused arguments on class object

### ISSUE THREAD

**Issue by divineniiquaye** [nette/di#251]
Nette Di has a bug working with classes where addition arguments are passed unto the `createInstance` method.

Let me explain: I've been working with [Cycle ORM](https://github.com/biurad/cycle-bridge) with [Nette DI](https://github.com/nette/di), the project was designed in a way to pass arguments to a repository class object. Some arguments where not meant to be passed on default ` Cycle\ORM\Select\Repository` class object, but could be used in an extended repository class object if available in additional arguments.

There's a confusion here, some values found in additional arguments can be autowired, whilst others just cannot be. This bug occurs in the [`Resolver` class object Line 527](https://github.com/nette/di/blob/master/src/DI/Resolver.php#L527)

![Bug Image](https://user-images.githubusercontent.com/53147395/102012238-1c2fdf00-3d41-11eb-9ce5-24d05c3fecc9.png)

My sugguest is, I think it will be relevant to allow unused arguments on nette di, in order to work with projects like [Cycle ORM](https://github.com/cycle/orm). My solution below is what I could think of, but if a better solution can be applied that will be cool:

*BEFORE*:
```php
if ($arguments) {
    throw new ServiceCreationException('Unable to pass specified arguments to ' . Reflection::toString($method) . '.');
} elseif ($optCount) {
    $res = array_slice($res, 0, -$optCount);
}
```

*SOLUTION*
```php
if ($optCount) {
    $res = array_slice($res, 0, -$optCount);
}
```

**Comment by milo** [comment]
Why would you pass more params than declared in constructor? Such params are just lost.

**Comment by divineniiquaye** [comment]
> Why would you pass more params than declared in constructor? Such params are just lost.

Argument aren't lost, they were passed to [Cycle ORM](https://github.com/cycle/orm) repository class and will continue to exist until it can be resolved if required.

This diagram explains what I mean:
![image](https://user-images.githubusercontent.com/53147395/102014585-974bc200-3d4e-11eb-8394-ebd3178b2a79.png)

The circled blue area, are the original arguments passed to the class object, and the circled red area, contains the arguments left to be passed.

An exception thrown on that is problematic, especially working with projects such as [Cycle ORM](https://github.com/cycle/orm).

**Comment by dg** [comment]
The [Cycle\ORM\Select\Repository](https://github.com/cycle/orm/blob/a4d436656d80944c8e3dda02741deca0f5aef856/src/Select/Repository.php#L30) has only one parameter named `$select`. So DI is unable to pass arguments `orm` and `role` because it doesn't know its order.

PHP 8 throws the same exception when you try to do this:

```php
$repo = new Cycle\ORM\Select\Repository(select: $select, orm: $orm, role: 'user');
```
