### ISSUE TITLE
Injecting the Container into the service should generate a notice

### ISSUE THREAD

**Issue by janbarasek** [nette/di#254]
The `getContext()` method in the Presenter newly generates a message that this **method is deprecated** and a DIC should be used.

The same problem with the "dirty" application design is also injecting the `Container` into the service constructor, which should also generate a notice so that the developer prefers to use to inject specific services or a collection of services because this design pattern is so magic.

If a service really needs to use the Container, it should be injected, for example, with the `setContainer()` method (in setup), which bypasses the developer's error message and gets the Container anyway.

What do you think? Thank you.

**Comment by dg** [comment]
There is no reason for this, it is a normal object.

**Comment by mabar** [comment]
Setter is more dirty than constructor. In case dependency is required by class to work, setter is nonsense.
Using container directly is absolutely okay as long as the obtained dependency is configurable from outside. E.g. all factories and accessors generated by nette/di use container directly for lazy-loading.
Presenter is just not the case, where Container is used in IoC-compatible manners
