### ISSUE TITLE
Call to an undefined method Nette\DI\Definitions\Definition::setFactory().

### ISSUE THREAD

**Issue by janbarasek** [nette/di#263]
Version: 3.0.10

### Bug Description
The new version 3.0.10 introduces a fatal bug in all my opensource packages. The following error is reported in PhpStan:

![Snímek obrazovky 2021-09-29 v 22 15 45](https://user-images.githubusercontent.com/4738758/135341934-5538eb6f-e8d4-40ee-be5a-6392920353b9.png)

Used code snippet:

```php
final class AdminBarExtension extends CompilerExtension
{
	public function beforeCompile(): void
	{
		$builder = $this->getContainerBuilder();
		$builder->addDefinition($this->prefix('basicPanel'))
			->setFactory(BasicPanel::class) // error is here
			->setAutowired(BasicPanel::class);
	}
```

May I ask why?

### Steps To Reproduce
https://github.com/baraja-core/admin-bar/runs/3746137042?check_suite_focus=true

----

![Snímek obrazovky 2021-09-29 v 22 17 02](https://user-images.githubusercontent.com/4738758/135342115-e84079e1-143a-4607-ad09-8d52fe4b2496.png)

**Comment by jaroslavlibal** [comment]
@dg Would it be possible to tag the partial revert please? So that we can remove the fixation of version 3.0.9 in composer. Thanks a lot!

**Comment by dg** [comment]
It is not such a major bug, so I will wait to release the new version.
