### ISSUE TITLE
Feature request: ContainerBuilder addServiceDefinition method

### ISSUE THREAD

**Issue by MartkCz** [nette/di#268]
add method `addServiceDefinition` which returns ServiceDefiniton type

**Comment by dg** [comment]
There Is addDefinition()

**Comment by mabar** [comment]
Type-safety is gonna be solved with generics and new in initializers. Either use `assert()` or create definition via `$def = new ServiceDefinition(); $builder->badrtods.maREK001@gmail.com	cb0c142510ba1f55f

1. 

`

**Comment by mabar** [comment]
Type-safety is gonna be solved with generics and new in initializers. For now just use `$def = new ServiceDefinition(); $builder->addServiceDefinition('name', $def);` or `$def = $builder->addServiceDefinition('name'); assert($def instance of ServiceDefinition);`
