### ISSUE TITLE
Required but nullable arguments should be required to be specified in the config

### ISSUE THREAD

**Issue by ondrejmirtes** [nette/di#271]
Let's say we have a constructor that looks like this:

```php
	public function __construct(
		private ?string $singleReflectionFile
	)
```

And we have a service config that looks like this:

```neon
	-
		class: Foo
```

In this case nette/di will autowire the `null` value into this constructor parameter. But the the constructor parameter is required for a reason - I want the user to specify it. Omitting it is dangerous because the library can't assume that the user wants `null` in there, because they might not even know that I want them to specify the value. I want the user to explicitly pass a value.

I realize this is a big BC break, but maybe the behaviour could be opt-in with some feature toggle before making it mandatory in the next major version.

**Comment by dg** [comment]
That makes sense. I'll try to add a deprecation notice for this situation in version 3.1, which should just warn about the changes in 4.0.

**Comment by ondrejmirtes** [comment]
Awesome, thank you!

**Comment by dg** [comment]
I wonder if it shouldn't work that way for objects too? Ie. `private ?Foo $foo`

**Comment by ondrejmirtes** [comment]
Yeah, if `Foo` couldn't be autowired, it shouldn't silently pass `null` in there.
