### ISSUE TITLE
Serialization of Closure is not allowed Exception thrown when using new in constructor (PHP 8.1 feature)

### ISSUE THREAD

**Issue by patrickkusebauch** [nette/di#273]
Version: 3.0.11

### Bug Description
Serialization of `Closure` is not allowed Exception thrown when using `new in constructor` (PHP 8.1 feature).

Caused by `return md5(serialize($hash));` from `DependencyChecker.php:165`

![Screenshot from 2021-12-09 21-55-55](https://user-images.githubusercontent.com/1620948/145474336-11b322bb-a8ce-49f2-ac56-7d046242cb97.png)

### Steps To Reproduce
Write and register class with constructor like this:
```
    public function __construct(
        $clientCredentials,
        ?SignatureInterface $signature = null,
        private GuzzleHttpClient $httpClient = new GuzzleHttpClient()
    ) {}
```

### Expected Behavior
Successfully compile DI container.

**Comment by dg** [comment]
Fixed
