### ISSUE TITLE
Invalid type 'Nette\DI\?T' when accessing `Container#getByType()` from DI config

### ISSUE THREAD

**Issue by dakur** [nette/di#274]
Version: 3.0.11, bug present as of 3.0.10

### Bug Description

If you use `Container#getByType()` inside of NEON configuration, it fails on resolving its return type – from `Helpers#getReturnTypeAnnotation()` it is returned `Nette\DI\?T`.

More generally, I believe (have not tried) accessing any class with method having generic return type will fail.

### Steps To Reproduce
In `nette/web-project`, create this class:

```php
namespace App;
final class FakeContainer
{
	/**
	 * copied from Container#getByType()
	 * @template T
	 * @param class-string<T> $type
	 * @return ?T
	 */
	public function getService(string $type)
	{
		return null;
	}
}
```

In `services.neon`, use it:

```neon
services:
	- App\FakeContainer::getService(HomepagePresenter::class)
```

![image](https://user-images.githubusercontent.com/9862581/145772312-41f914fe-e7b0-4d93-9d4c-7d5dac38face.png)

### Expected Behavior
Run, not to fail with type check.

**Comment by dakur** [comment]
Note that if you change `@return ?T` to `@return T`, it fails with different error. I think that is related.

![image](https://user-images.githubusercontent.com/9862581/145772538-ed85e383-2631-4e6e-b297-9ae9b9a5d1b6.png)

**Comment by milo** [comment]
What if you declare it as following?

```php
public function getService(string $type): object
{}
```

**Comment by dakur** [comment]
That doesn't seem to help..

![image](https://user-images.githubusercontent.com/9862581/145808528-5a148939-be56-468d-8cd8-8e4e7bb56e9b.png)

**Comment by JanTvrdik** [comment]
This seems like expected behavior, generics are not supported.

**Comment by dg** [comment]
DI doesn't support generics and I don't plan to implement it, in fact I plan to remove support for @return annotation completely in version 4.  But you can specify the type directly in the config:

```
services:
	- factory: App\FakeContainer::getService(HomepagePresenter::class)
	  type: HomepagePresenter
```

**Comment by mabar** [comment]
Is there any reason to not support `object`?

**Comment by dg** [comment]
It is always object.

**Comment by mabar** [comment]
I mean it's bit confusing from the user's point of view that object is not allowed return type of method. But in reality it's okay and we just have to declare more specific type in neon because library is not able to infer it from generics itself. Some hint like "I don't understand object / Foo&Bar / ... type, could you change the type to some specific class or add the type to service definition?"

**Comment by dg** [comment]
It's not that it doesn't understand it, it understands and doesn't allow it. So return type is not expected to be nullable/union/intersection/built-in type.

**Comment by dakur** [comment]
@dg Thank you, but the suggestion did not help for the example code – it fails with `Return type of App\FakeContainer::getService() is not expected to be nullable/union/intersection/built-in, 'object' given`.

It didn't help in real code either as I already have `type` already set there. So maybe there is also bug in `type` not making any effect?

For illustration, I attach real code:

```neon
pages.filesystem:
	type: League\Flysystem\Filesystem
	factory: @outerContainer::getByType(PageFilesystemProvider)::getPageFilesystem()
	autowired: false
```

Just an explanation of our use-case: we have app and model container – app is outer, model inner. App can use services from inner (model) container, but model container needs some bindings to the app world – e.g. translator, identity etc. – thus this `@outerContainer::getByType()` calls.

I understand that such usage of DI can be a bit marginal/edge-case (🤷‍♂️❓), but I still think it reveals some bug(s) in DI resolver/type checking.

**Comment by dg** [comment]
Yeah, I finally get it, the problem is the throwing of the exception.

So it should actually work that if the return type is 'object', it will ignore the @return annotation, right?

**Comment by dakur** [comment]
> So it should work that if the return type is 'object', it will ignore the @return annotation and 'object' too, right?

Not pretty sure. I don't have such knowledge of DI to tell if this is solution to the root cause, sorry. I'm not even sure I know what is the root cause actually.

But yeah, the problem is that it throws exception instead of returning `HomepagePresenter`/`PageFilesystemProvider` instance.

**Comment by dg** [comment]
Try v3.0-dev, now is should work.

```php
final class FakeContainer
{
	/**
	 * @template T
	 * @param class-string<T> $type
	 * @return ?T             
	 */
	public function getService(string $type): ?object  // @return ?T is ignored now
	{
	}
}```

**Comment by dakur** [comment]
@dg I'm sorry, but it's still the same. From the referenced commit, I don't even understand how it should help as there was just added one failing scenario.

But if you plan remove generic annotation from `Container#getByType()` in v4 (especially the `@return ?T` line), that helps, so I can wait with update until it is published.

**Comment by dg** [comment]
Try to create some minimal project, I really don't understand what is not working for you.

Btw what is the hash in `Container#getByType()`?

**Comment by dg** [comment]
I mean `#` in `Container#getByType()` Does it have any special meaning?

**Comment by dakur** [comment]
I think it's a way how to talk about class' method without associating it with static or non-static usage. I could write `Container::getByType()` as well.

**Comment by dg** [comment]
Oh, I've never seen that before. I see `::` as way how to refer to a class method without associating it with static or non-static usage.

**Comment by dg** [comment]
Oh, I see what's going on. The problem is the calling of another method, when DI tries to evaluate over which object is called

```neon
services:
	- App\FakeContainer::getService(HomepagePresenter::class)::anotherMethod()
```

**Comment by mabar** [comment]
Evaluation is done to call the method properly, right? 

It would be nice to have PHP-like syntax for constants/properties/(static) methods in neon.
e.g. `@Nette\Http\IRequest->getUrl()->getBasePath()` instead of `@Nette\Http\IRequest::getUrl()::getBasePath`.
DI would not have to evaluate these calls.

(sorry for asking for complicated changes)

**Comment by dakur** [comment]
Looks like it works, thank you!
