### ISSUE TITLE
Service constructor: add native support for strict array type.

### ISSUE THREAD

**Issue by janbarasek** [nette/di#277]
Hello,

In the DI service entry, I can request a collection of services that meet the same interface.

For example:

```php
/**
 * @param OrderPaymentGatewayInterface[] $providers
 */
public function __construct(array $providers) { ... }
```

If I am using PhpStan level 9 and want to specify the exact key type in an array, DIC cannot inject services:

```php
/**
 * @param array<int, OrderPaymentGatewayInterface> $providers
 */
public function __construct(array $providers) { ... }
```

The challenge is to add native support for composite array notation with exact key definition. In the first phase, I propose to support only the `int` key type and mark all others as unsupported.

Why support this notation? Much more strict type within the service.

Thanks.

**Comment by JanTvrdik** [comment]
The keys in `$providers` are meaningless. Why do you need to ensure that they are integers?

**Comment by janbarasek** [comment]
Because other application layers can use strict types that expect a service list, for example. Now I have to do this retyping applicationally. Nette could provide the services directly in strict form.

**Comment by JanTvrdik** [comment]
Can you given example? PhpStan seems to be fine with `OrderPaymentGatewayInterface[]`
https://phpstan.org/r/89126eed-47d0-4c4d-8536-505ae2fa3a46

**Comment by mabar** [comment]
I discussed posibility to add a config option to require array keys by PHPStan with Ondrej. Using keys of undefined type is a type-safety loophole which is safer to not allow at all.
Also some coding standard rules require generic type syntax for codebase style consistency, like `SlevomatCodingStandard.TypeHints.DisallowArrayTypeHintSyntax`

It's not really necesity to have numeric keys in DI services, it would just make working with strictest standards easier.
