### ISSUE TITLE
Tracy panel for DI is too slow

### ISSUE THREAD

**Issue by jakubboucek** [nette/di#279]
Version: 3.0.12

### Bug Description
Rendering of DIC Tracy panel is too slow. See [my snapshot of rendering DI services times](https://docs.google.com/spreadsheets/d/1ZmW8I9dE59dXuB0f53PW-DFpFr02rqGLkE2KEqUm_3I/edit).

The main trouble is with services:

- `application.application`
- `latte.latteFactory`

Both of them services contains reference to DI container and it's cause to dump whole DI container in DI Panel.

![image](https://user-images.githubusercontent.com/1657322/156906778-dff42d46-4597-4ee1-b9d8-6755bebef593.png)

### Possible Solution
I have 2 ideas to fix that:

- Skip re-dumping whole DI Container in DI Tracy Panel.
- Allow user to configure DI extension to turn-off dump service instance, instead only print service name.

**Comment by dg** [comment]
Is it fixed in master?

**Comment by dg** [comment]
fixed
