### ISSUE TITLE
Arguments are not unpacked when creating instance in DI extension

### ISSUE THREAD

**Issue by VojtechBuba** [nette/di#286]
Version: 3.1.2

### Bug Description
I have DI extension where i register service and pass some arguments to constructor. In class constructor i use splat operator. In version 3.1.1 everything works fine, but in version 3.1.2 the array i pass as an argument is not spread and i get Type error that class expects Web instance but array is passed. 

### Steps To Reproduce
Class looks like this
```php
class Config
{
	public function __construct(
		Web ...$webs
	)
	{
		$this->webs = $webs;
	}
```

and in DI extension 
```php
$builder->addDefinition($this->prefix('multiwebConfig'))
			->setFactory(Config::class, [
				'webs' => array_map(
					static fn (array $web) => new Web(
						$web['id'],
						$web['defaultLanguage'],
						$web['languages'],
					),
					$config['webs'],
				),
			]);
```

### Expected Behavior
Array as an argument is spread

**Comment by dg** [comment]
Duplicate to #289
