### ISSUE TITLE
Decorators not called

### ISSUE THREAD

**Issue by dakur** [nette/di#287]
Version: 3.1.2

Hi, couple of months ago, I made simple `composer update` after which data from our web application stopped being collected by Google Tag Manager because of decorator suddenly stopped being called in the codebase:

```php
decorator:
	App\FrontModule\Presenters\BasePresenter:
		setup:
			# tried var_dump() inside of the showGoogleTagManager() and nothing was rendered
			- showGoogleTagManager(%gtm%) # gtm is boolean
```

These packages were updated at the time:
- `contributte/di`: 0.5.2 -> 0.5.3
- `nette/di`: 3.0.2 -> 3.0.13

Now, I'm on nette/di 3.1.2 and still it's not called.

I've ensured that the extension altogether behaves as expected:

```neon
# correctly fails that decoratorFAIL is not an extension
decoratorFAIL:
	App\FrontModule\Presenters\BasePresenter:
		setup:
			- showGoogleTagManager(%gtm%) # gtm is boolean

# correctly fails that such class does not exist
decorator:
	App\FrontModule\Presenters\NONEXISTENTCLASS:
		setup:
			- showGoogleTagManager(%gtm%) # gtm is boolean

# correctly fails with unexpected item setupFAIL
decorator:
	App\FrontModule\Presenters\BasePresenter:
		setupFAIL:
			- showGoogleTagManager(%gtm%) # gtm is boolean
```

However, calling non existent or setting private property won't fail. So it looks like that the extension technically works, but decorators are not called:

```neon
decorator:
	App\FrontModule\Presenters\BasePresenter:
		setup:
			- something() # no such method in presenter
```

Is it a bug, or didn't I notice some change?

Thank you.

**Comment by dakur** [comment]
Hm, I've tried it also in fresh nette project and the decorator was called as expected. So it will be probably in some other place, sorry for the issue.

**Comment by mabar** [comment]
It may be related to presenters being automatically registered as services (optionally). I guess your presenter is created in runtime and so does not exist in generated DIC and DecoratorExtension can't apply its setup.

Simplest way to fix it is register presenter as a service manually. Otherwise you will have to debug, why your presenter is not found by ApplicationExtension

**Comment by dakur** [comment]
Thanks for your answer! Yes, you are right, if I register e.g. `HomepagePresenter`, the decorator is finally called. But I don't understand why it worked before the update. 🤷‍♂️

Also, not sure what to do when I need to decorate abstract presenter. Do I have to list all of the child presenters? Maybe some `GTMConfig` service would be better then I guess..

**Comment by mabar** [comment]
Did you also update nette/application? Or do you have `application:` options like scanComposer, scanFilter, scanDir set?

> Do I have to list all of the child presenters?

Yes, decorator works with service definitions, each presenter must be available as a service.

**Comment by dakur** [comment]
>Did you also update nette/application?

No

> Or do you have application: options like scanComposer, scanFilter, scanDir set?

Yes, `scanDirs: false`

**Comment by dakur** [comment]
There was probably some perf improvement in nette/di which caused that decorating unscanned presenters stopped working. It makes sense actually when I chose not to scan for presenters. 🙂 Did forget about that setting.
