### ISSUE TITLE
Dynamic parameter does not work in static parameter

### ISSUE THREAD

**Issue by ondrejmirtes** [nette/di#291]
Version: 3.1.2

### Bug Description

The documentation says (https://doc.nette.org/en/application/bootstrap#toc-dynamic-parameters):

> We can also add dynamic parameters to the container, their different values, unlike static parameters, will not cause the generation of new DI containers. Environment variables could be easily made available using dynamic parameters. We can access them via `%env.variable%` in configuration files.

When I try this in practice, the parameter value is `null` instead of the expected value of expanded env variable.

### Steps To Reproduce

I created a minimal project that shows this problem: https://github.com/ondrejmirtes/nette-di-dynamic

The script test.php:

```php
<?php

require_once __DIR__ . '/vendor/autoload.php';

$configurator = new Nette\Bootstrap\Configurator;
$configurator->setTempDirectory(__DIR__ . '/temp');
$configurator->addConfig(__DIR__ . '/test.neon');
$configurator->addDynamicParameters([
	'env' => getenv(),
]);
$container = $configurator->createContainer();

var_dump($container->parameters['test']);
```

The neon file test.neon:

```neon
parameters:
	test: %env.NETTE_TEST%/foo
```

How to run:

```
export NETTE_TEST=foo
php test.php
```

### Expected Behavior

```
string(7) "foo/foo"
```

### Actual Behaviour

```
NULL
```

**Comment by ondrejmirtes** [comment]
In theory it should work, it's just that the compiled DIC needs to look different.

**Comment by mabar** [comment]
I see your point, you just confused me with the title. Reference to a dynamic parameter in another parameter may work, esentially making the referecing parameter dynamic instead of being static

**Comment by ondrejmirtes** [comment]
I did a few more tests: https://github.com/ondrejmirtes/nette-di-dynamic/commit/475447bfa25f0ff477e749ab5ad74e2de680658d

The result of the script is now:

```
NULL
string(7) "foo/foo"
string(7) "foo/foo"
```

So when used as a service argument, it works as expected. The compiled container looks like this:

```
($this->parameters['env']['NETTE_TEST']) . '/foo'
```

It would be awesome if the `parameters` array could look like this too.

**Comment by dg** [comment]
In other words, you want that instead of lazy evaluation, there should be immediately evaluation at the beginning. That might work, of course, but it's a trade-off.

**Comment by dg** [comment]
I'm thinking there might be a compromise. Parameters like `%env.NETTE_TEST%/foo` can be resolved right away. Parameters that call methods like `@service::foo()` can continue to resolve lazy.

I tried implement it in 3.2-dev

**Comment by ondrejmirtes** [comment]
Looks like 3.2-dev includes a lot of BC breaks (removes current features) which it should not so unfortunately I can't test it: https://github.com/nette/di/commits/v3.2

Would be great if 3.2 still supported PHP 7.2+ which is what PHPStan supports. Although I can work around that if needed.

**Comment by ondrejmirtes** [comment]
1) Minor versions should never contain any BC breaks.
2) nette/di is used by PHPStan users through custom .neon files so any changes to supported NEON syntax can break PHPStan for someone. I think that's the case of this commit https://github.com/nette/di/commit/3b3c1adff31093b008d10df8fae172e8603a0345 This is also a BC break for generated factories from what I understand https://github.com/nette/di/commit/5c36951b3c115039918bcbe16868367032adae64.

When upgrading to nette/di 3.1.3 I also had to silence E_USER_DEPRECATED with this commit https://github.com/phpstan/phpstan-src/commit/c43ac096f511c922af22cf6024208ca611d30a22 when creating the DI container because I don't want to bother PHPStan users with these deprecations: https://github.com/phpstan/phpstan-src/commit/c43ac096f511c922af22cf6024208ca611d30a22 (in the future I'd probably transform the neon array on user's behalf before passing it to nette/di).

**Comment by dg** [comment]
If you encounter any problems, you'd better write me and not mute E_USER_DEPRECATED. 

I don't consider it as a BC break to remove things that have been throwing out E_USER_DEPRECATED since the previous version, two years old. But if you don't play the game, of course it can be a problem.

**Comment by ondrejmirtes** [comment]
Yeah, personally I wouldn't use any deprecated things in my own applications and fix them immediately, but PHPStan exposes nette/di to its users through the neon config format, and I would have to provide some easy migration path so that my users are not bothered with these deprecations.

**Comment by dg** [comment]
And which ones in particular did they encounter, do you remember?

**Comment by ondrejmirtes** [comment]
@dg I haven't released a version that wouldn't silence E_USER_DEPRECATED from nette/di so I didn't really get that feedback, but I think the most common one is the deprecated `class` key for services, as can be seen very frequently in 3rd party packages like https://github.com/shipmonk-rnd/phpstan-rules/blob/master/rules.neon.

**Comment by ondrejmirtes** [comment]
Thank you! I'm gonna try it right away.

**Comment by dg** [comment]
Hmm, that's strange, `class` should work normally...

**Comment by ondrejmirtes** [comment]
`%env%` in parameters now works as expected! 🎉 Thank you very much!

As for `class` in `services`: If I un-silence E_USER_DEPRECATED, I get many of these errors:

```
PHP Deprecated:  Service '9': option 'class' should be changed to 'type'. in vendor/nette/di/src/DI/Extensions/DefinitionSchema.php on line 130
```

It still works, but I don't want to put this burden on PHPStan users.

**Comment by dg** [comment]
How is it used?

```neon
- class:: ClassName                 # should work
- class:: ClassName(arg, arg)  # historically, this has worked by mistake
```

**Comment by ondrejmirtes** [comment]
I just debugged it and entries like this are reported as deprecated:

```neon
	-
		class: PHPStan\Php\PhpVersion
		factory: @PHPStan\Php\PhpVersionFactory::create

	-
		class: PHPStan\Php\PhpVersionFactory
		factory: @PHPStan\Php\PhpVersionFactoryFactory::create
```

Which is okay but I still don't want to force PHPStan users to rewrite them :)

**Comment by dg** [comment]
I'll try to find a solution...

**Comment by mabar** [comment]
@ondrejmirtes Wouldn't be a way to resolve this in the long run to allow deprecation notifications to be turned on? So that PHPStan users would not be bothered, but the extension developers could make the necessary changes. I believe most users don't use any things from di or neon that may change.

**Comment by ondrejmirtes** [comment]
TBH in the long run I want a different PHPStan-specific config format, probably based on objects that work with IDE autocompletion and can be validated with PHPStan analysis 😊

**Comment by dg** [comment]
@ondrejmirtes see 8fd9b4a885017cd33ba6e3fad0b74ac4650c9b09

**Comment by dg** [comment]
It will work a little differently, instead of `$container->parameters['test']` will work `$container->getParameter('test')`.

**Comment by kipanshi** [comment]
This new patch version 3.1.4 broke codeception tests in our app based on REMP CRM,
we have the codeception config:
```
paths:
  tests: tests
  output: tests/_output
  data: tests/_data
  support: tests/_support
  envs: tests/_envs
actor_suffix: Tester
bootstrap: _bootstrap.php
extensions:
  enabled:
    - Codeception\Extension\RunFailed
modules:
  enabled:
    - Db:
        dsn: 'mysql:host=%CRM_DB_HOST%;dbname=%CRM_DB_NAME%'
        user: '%CRM_DB_USER%'
        password: '%CRM_DB_PASS%'
params:
  - tests/_data/crm/.env
```

and in .env file:
```
CRM_DB_HOST=localhost
CRM_DB_NAME=crm_test
CRM_DB_USER=root
CRM_DB_PASS=123
```

And getting error
[Exception] DB prepare error in command: 'phinx:migrate' |  | Nette\DI\InvalidConfigurationException: The item 'database › default › dsn' expects to be Nette\Schema\DynamicParameter or string, object Nette\DI\Definitions\Statement given. in /var/www/crm/vendor/nette/di/src/DI/Compiler.php:293

Worked fine in the version 3.1.3.

**Comment by kipanshi** [comment]
I think it's best to open a new issue for it.

**Comment by dg** [comment]
@kipanshi fixed
