### ISSUE TITLE
SearchExtension: compatible with trait Nette\StaticClass

### ISSUE THREAD

**Issue by h4kuna** [nette/di#292]
Hello if I use trait [Nette\StaticClass](/nette/utils/blob/master/src/StaticClass.php) the extension Search automatically register the class like a service to container.

There are two ways:
1) in trait Nette\StaticClass change visibility of constructor from final public to private. The [ReflectionClass::isInstantiable](https://www.php.net/manual/en/reflectionclass.isinstantiable.php) will work fine. I prefer

2) add exception for this trait to Search extension

> I know if you have registered static classes, it doesn't matter, because these classes are not in constructors, but this is no reason to register in container.

Example of bad behavior:

```php
namespace Uget;

use Nette\StaticClass;

final class Tools
{
	use StaticClass;
}
```
In Container i see
```php
	public function createService017(): Uget\Tools
	{
		return new Uget\Tools; // throw exception
	}
```

I must add to ignore
```neon
search:
	exclude:
		classes:
			- Uget\Tools
```

**Comment by dg** [comment]
Yes, it's better to use a private constructor.
