### ISSUE TITLE
Compiler error in process schema after update to 3.1.4

### ISSUE THREAD

**Issue by kipanshi** [nette/di#296]
Version: 3.1.4

### Bug Description
This new patch version 3.1.4 broke our app based on REMP CRM,
the environment config based on service doesn't work anymore.

app/config.neon:

```
database:
    default:
        dsn: @environmentConfig::getDsn()
        user: @environmentConfig::get('CRM_DB_USER')
        password: @environmentConfig::get('CRM_DB_PASS')
        options:
            lazy: yes
```

And getting error
```
[Exception] DB prepare error in command: 'phinx:migrate' | | Nette\DI\InvalidConfigurationException: 
The item 'database › default › dsn' expects to be Nette\Schema\DynamicParameter or string, 
object Nette\DI\Definitions\Statement given. in /var/www/crm/vendor/nette/di/src/DI/Compiler.php:293
```

Worked fine in the version 3.1.3.

### Steps To Reproduce
No demo app yet, can do it later, it should be reproduciable by using the syntax above 

### Expected Behavior
The params are evaluated properly and no error produced.

**Comment by dg** [comment]
fixed

**Comment by kipanshi** [comment]
Thank you!
Checked the new version and confirm that issue is fixed.
