### ISSUE TITLE
Circular reference detected for variables

### ISSUE THREAD

**Issue by Gappa** [nette/di#297]
Version: 3.1.7

### Bug Description
When referencing another variable an exception is thrown:

```
Nette\InvalidArgumentException
Circular reference detected for variables: test.foo.
```
![image](https://github.com/nette/di/assets/749981/5d71ad08-e83a-4e2f-b86a-5e24de0eb609)

### Steps To Reproduce

parameters.neon

``` neon
parameters:
	test:
		foo: 'foo'
		bar: 'bar'
		foobar: %test.foo%%test.bar%
```

### Expected Behavior

Variable is correctly expanded and concatenated. 

### Possible Solution

N/A, reverting to 3.1.6 as a workaround.

**Comment by elcheco** [comment]
@Gappa @dg 

I had the same issue after upgrading from 3.1.5 to 3.1.7
It is also pointing into the config file parameters...
After downgrading back to 3.1.5 everything works fine again...

**Comment by forrest79** [comment]
The same here, we had to downgrade to 3.1.6.

**Comment by dg** [comment]
Can you test if it works in the 3.1-dev version?

**Comment by Gappa** [comment]
It works with `v3.1.x-dev 4420639` 👍

**Comment by forrest79** [comment]
The same here :+1:
