### ISSUE TITLE
wrong inject of variables after update 3.1.6 > 3.1.7

### ISSUE THREAD

**Issue by lukasnovot** [nette/di#298]
Version: v3.1.7

### Bug Description
When injected variable is named exactly like injected interface (for example public ISomeGridFactory $ISomeGridFactory) throw Nette\DI\ServiceCreationException - class $ISomeGridFactory not found. If I rename to diffrent variable name ( public ISomeGridFactory $someGridFactory) it works.

### Steps To Reproduce
Rename inject variable exactly to name of injected interface - public ISomeGridFactory $ISomeGridFactory;

### Expected Behavior
I think it shouldn't depend on the variable name

**Comment by Gappa** [comment]
Mentioned here:

- https://forum.nette.org/cs/36175-di-v3-1-7-exception-pri-pouziti-inject#p225107

**Comment by dg** [comment]
fixed
