### ISSUE TITLE
Nette\DI\Config\Loader::load($filePath) loads string parameter '@12345' as string '@@12345'

### ISSUE THREAD

**Issue by forgie1** [nette/di#300]
Version: v3.1.8

### Bug Description
Error was tested on one of this examples: https://github.com/nette-examples (no other custom code).

`Nette\DI\Config\Loader::load($filePath)` loads string parameter `'@12345'` as `'@@12345'`

e.g. file:
```.neon
parameters:
	errorReading: '@12345'
```
will be read to array:
```php

[
    'parameters' => [
        'errorReading' => '@@12345'
    ]
]

```

The same way string `errorReading2 => "%12345%"` will cause `Nette\InvalidArgumentException`, because of attempt to find parameter 12345.

### Expected Behavior
string  `'@12345'` keeps beeng string `'@12345'`

**Comment by dg** [comment]
Why do you use Config::load?

**Comment by forgie1** [comment]
Acctually I don't.

I just use: `\Nette\Bootstrap\Configurator::addConfig($filePath)`;
But I didn't debug further than to `Nette\DI\Config\Loader::load($filePath)`.

**Comment by dg** [comment]
And what is the problem?
