### ISSUE TITLE
Date in section parameters throw exception

### ISSUE THREAD

**Issue by h4kuna** [nette/di#310]
Hello,

Version: v3.2.0

### Bug Description
In section `parameters` I have defined date, in previous version, this setup was correctly translated to DatetimeImmutable. In this version, end with exception *Error*: **Object of class DateTimeImmutable could not be converted to string**

### Steps To Reproduce
```neon
parameters:
	foo: 2014-01-01
```

### Expected Behavior
Same behavior like previous version 3.1.*

### Possible Solution
For this moment, I wrap by quotation marks and factory create DatetimeImmutable.
```neon
parameters:
	foo: '2014-01-01'
```

**Comment by dg** [comment]
already fixed
