### ISSUE TITLE
Performance issue of magic methods, getters and setters

### ISSUE THREAD

**Issue by matej21** [nette/di#41]
I was wondering what takes so long while nette is generating container. And surprisingly (or not?) - it's a magic!
This is xdebug profiler output for my app:
![di-magie2](https://cloud.githubusercontent.com/assets/1276059/5964503/df68db2c-a7f4-11e4-9f20-5a23a7ca3873.jpg)
(self and inclusive cost is in percent)

I've tried to make some optimization (replacing magic `@method` in nette/di and nette/phpgenerator with proper methods and removing usage of magic getters/setters) and this is the result:
![di-magie3](https://cloud.githubusercontent.com/assets/1276059/5964537/43e94e56-a7f5-11e4-81d4-0d85a8116d87.jpg)

Ouch!

Do you agree with removing this magic? Should I prepare PR?

**Comment by fprochazka** [comment]
Keep in mind both `->class` and `->setClass` variants should keep working. But apart from that, yes! Let's kill the magic in the core of Nette :+1:

**Comment by JanTvrdik** [comment]
:+1: I have this on my todolist for a while. If you do it, I can focus on other stuff.

**Comment by JanTvrdik** [comment]
BTW: If you [upload](http://blog.blackfire.io/cli-upload.html) those cachegrind files to Blackfire to compare them.

**Comment by dg** [comment]
Go for it!
