### ISSUE TITLE
Občas nemůže otevřít Nette.Configurator/Container_0000f000f0.php

### ISSUE THREAD

**Issue by besir** [nette/di#56]
Ahoj,
obcas v průběhu používání applikace se mi stane, že dostanu http://postimg.org/image/qokdch9lj/
Není to třeba žebych smazal cache a pak se to dělo, na jedné stránce při práci s ní po několika refreshích se mu to prostě občas nepodaří otevřít. 

Abych řekl pravdu, absolutně netuším jak to debugovat, ale když se podívám na disk tak tam ten file fyzicky existuje. Kdyby byl nějaký tip jak to pozorovat tak rád pomohu více.

**Comment by JanTvrdik** [comment]
Verze Nette? Dost možná pomůže https://github.com/nette/di/pull/37, současná implementace je trochu buggy.

**Comment by dg** [comment]
@JanTvrdik popisovaný stav to ale IMHO nevysvětluje…

**Comment by besir** [comment]
A za verzi nette se omlouvam, psal jsem ji na jabber a tady jsem pak zapomel... 2.3-beta2

**Comment by JanTvrdik** [comment]
@dg To máš pravdu, ale nic lepšího mě nenapadlo. Není možné, že se mu z nějakého důvodu builduje DI container při každém požadavku? Nebo není možné, že `is_file` vrací staré výsledky kvůli cache stat? Dost možná to bude issue specifická pro Vagrant.

**Comment by besir** [comment]
No každopádně se stable se mi to nestalo...

**Comment by dg** [comment]
@besir můžeš logovat, co přesně se před `require` děje?

**Comment by besir** [comment]
Pokusím se, ,doufám, že se mi na to povede narazit v nějakém rozumném čase. Dnes večer se tomu pověnuji...

**Comment by dg** [comment]
Díky

**Comment by besir** [comment]
Ted mě tak napadlo, že vždy se to stalo jen se zapnutou tracy, tedy v developerském režimu a na Vagrant stroji, ne pokud na nej pristupuji z venci, tedy jakoby v produkcnim rezimu. A na té stránce kde se to několikrát stalo tak jsou asi 4 ajax requesty. Mohlo tedy sehrát roli nějaké větší vytížení stroje (tedy pomalejší synchronizace adresářů) a k tomu to, že si to requesty mezi sebou smazali... protože nazev se vyrábí takto https://github.com/nette/di/blob/master/src/DI/ContainerLoader.php#L54 a je tudíž pokaždé stejný pokud se nezmění konfigurcae, což dává smysl, ale zřejmě to na řekněme pomalém DEV prostředí může dělat neplechu.

**Comment by dg** [comment]
@besir  Přetrvává to i v aktuální verzi 2.3.0?

**Comment by besir** [comment]
@dg Negativní
