### ISSUE TITLE
mysqli creation requires to specify all arguments

### ISSUE THREAD

**Issue by janedbal** [nette/di#57]
After migrating to version 2.3 I'm getting error ```Parameter $port in mysqli::mysqli() has no type hint, so its value must be specified``` when creating [mysqli](http://php.net/manual/en/mysqli.construct.php) (it has default values taken from ini settings) like this:

```yaml
    - mysqli(
        %database.host%,
        %database.username%,
        %database.password%,
        %database.database%
    )
```

This definitly worked on 2.2. To make it work as before, I must use:

```yaml
    - mysqli(
        %database.host%,
        %database.username%,
        %database.password%,
        %database.database%,
        ::ini_get(mysqli.default_port),
        ::ini_get(mysqli.default_socket)
    )
```

**Comment by dg** [comment]
What is your PHP version?

**Comment by janedbal** [comment]
PHP 5.4.35

**Comment by fprochazka** [comment]
@janedbal thank you for reporting this ;)

**Comment by dg** [comment]
BTW: the most mindfuck in this issue: method `mysqli::__construct` in fact does not exists…  Even is documented http://php.net/manual/en/mysqli.construct.php.
