### ISSUE TITLE
Parameters auto-resolution for generated factories depends on variable name

### ISSUE THREAD

**Issue by janedbal** [nette/di#60]
Following example:

```yaml
services:
    - ISomeControlFactory
```

```php
interface ISomeControlFactory {
    /** @return SomeControl */
    public function create(SomeEntity $someEntity);
}

class SomeControl {
    public function __construct(SomeEntity $entity) {}
}

class SomeEntity {}
```

leads to exception
```
Service 'XX_ISomeControlFactory': Service of type SomeEntity needed by SomeControl::__construct() not found. Did you register it in configuration file?
```

just because the parameter variables have different names.

**Comment by lookyman** [comment]
I believe this is intentional, the automatic argument resolution matches them by their name. It could probably be improved, but it's a freakin' magic as it is, and if I have to use the same argument names to actually be able to understand my own code, then I'd prefere to do that..

**Comment by enumag** [comment]
It is intentional. Mainly because constructor can contain other arguments that are either autowired or configured manually in config.neon or extension. I belive that different behaviour would be even more magical and could have some unexpected results.

The exception is wierd though. I will test it because the exception message should be different.

**Comment by lookyman** [comment]
When `SomeControl`'s constructor needs `SomeEntity`, it takes it from `ISomeControlFactory`'s `create` method's argument, when they match. When they don't, it tries to take it from `Container` (and ignores the one from the argument). That is why the exception message is what it is.

**Comment by enumag** [comment]
Yes I understand that. But I'd expect an exception to say somthing like 'Parameter '$someEntity' not found in 'SomeControl::__construct().'

**Comment by enumag** [comment]
@janedbal By the way the service doesn't have to be anonymous.

**Comment by castamir** [comment]
It leeds to "needle & haystack" problem... simply imagine 2 required parameters  of the same type (class) in `create()` method.

On the other hand, exception message should be better

**Comment by enumag** [comment]
I tried to implement better exception but it broke [this test](https://github.com/nette/di/blob/master/tests/DI/ContainerBuilder.factory.params.phpt#L21-L24). It means that the arguments from create method can be used in setup, not necessarily in constructor. Which means the exception can't be improved.
