### ISSUE TITLE
Missing Exception - ServiceCreationException

### ISSUE THREAD

**Issue by whipsterCZ** [nette/di#68]
Fatal Error  - Class 'Nette\DI\Extensions\ServiceCreationException' not found 

chybí jmenný prostor Extensions

**Comment by enumag** [comment]
Already fixed. https://github.com/nette/di/commit/c658314b1bb9b289e1e989d6f257b49d8f8f6373

**Comment by whipsterCZ** [comment]
Chyba je opravená, nicméně přes composer se mi pořád stahuje neopravená verze

**Comment by dg** [comment]
Protože zatím nevyšla nová verze.
