### ISSUE TITLE
Autowiring fails when using type hint in method

### ISSUE THREAD

**Issue by Lukeluha** [nette/di#69]
I have something like this:
    
    namespace App\Forms;
    use App\Model\Item;

    interface IFormFactory
    {
	    /**
         * @param Item 
    	 * @return Form
	     */
	    function create($item);
    }

And this works. But when i add type hint into method param like this:
    
    namespace App\Forms;
    use App\Model\Item;

    interface IFormFactory
    {
	    /**
    	 * @return Form
	     */
	    function create(Item $item);
    }

Autowiring fails because generated Container looks like this:

    public function create($item) {
    ....
    }

and function create isn't same as it has been declared in interface.

**Comment by enumag** [comment]
Are you sure? I'm pretty sure this is covered in tests and it should work fine.

Try purging the temp dir and check that the typehint in `App\Forms\Form::__construct()` matches as well. If that doesn't help, copy the complete error message here.

**Comment by fprochazka** [comment]
@Lukeluha you haven't shown us the config

**Comment by matej21** [comment]
Could you show service definition in neon?

In nette < 2.3 you have to specify typehint in parameters section:
```yaml
services:
    -
        implement: App\Forms\IFormFactory
        parameters: [App\Model\Item item]
        arguments: [%item%]
```

Since 2.3 you can ommit both parameters and arguments section, so it could be simplified to this:
```yaml
services:
    - App\Forms\IFormFactory

**Comment by lukasslevercz** [comment]
This is my config file:
	formFactory:
		class: App\Forms\Form(%item%)
		implement: App\Forms\IFormFactory
		parameters: [item]

And really, when I attach type hint to parameter as @matej21 says, everything works fine. I'm using Nette 2.3.

Sorry for false alarm.
Thanks and issue can be closed.

However, simplified version without parameters isn't working for me, but this is another question :)

**Comment by hrach** [comment]
There is still a bug, isn't it?

**Comment by matej21** [comment]
@lukasslevercz  what is the name of the first parameter in `App\Forms\Form` contructor? it must be the same as the name of parameter in the `create` method of `App\Forms\IFormFactory` - `item`

**Comment by Lukeluha** [comment]
I've must misunderstood this, because App\Model\Item isn't service, it is Doctrine entity which is filled with different data every time. If everything of dependencies are services, simplified version works fine too.

22. 4. 2015 v 13:36, David Matějka <notifications@github.com>:

**Comment by matej21** [comment]
No, it should work even if it is not a service. This should work:
```yaml
- App\Forms\IFormFactory
```
```php
//IFormFactory
namespace App\Forms;

interface IFormFactory
{
    /** @return Form */
    public function create(\App\Model\Item $item);
}

//Form
namespace App\Forms;

class Form extends ....
{
    private $item;

    public function __construct(\App\Model\Item $item)
    {
        $this->item = $item;
    }
}
```

**Comment by Lukeluha** [comment]
Yes, it works exactly as @matej21. I've had to have some other bug in my code, but now everything work perfectly, thanks for advices :)
