### ISSUE TITLE
Support for ENV variables

### ISSUE THREAD

**Issue by mishak87** [nette/di#8]
Syntax could leverage support for arrays `a: %env.NAME%` with all variables in %env%.

Things to consider:
* Syntax for default values.
* Whitelist by default.
* Invalidate cache if used ENV has changed.
* Interface to access them in extensions. (to complement config and add requested ENVs to whitelist)

I have created [extension](https://github.com/rixxi/env) to add partial support for ENV variables. It has whitelist and default values and partial support for configs. Cache invalidation is not implemented

**Comment by janturon** [comment]
@fprochazka in my case, $_ENV was not working, but getenv() was:
`$configurator->addParameters(['env' => $_ENV]);`
and then %ENV.NAME%
