### ISSUE TITLE
Broken creation of services that have optional array constructor dependency

### ISSUE THREAD

**Issue by bazo** [nette/di#82]
if you have a class with constructor like this

    public function __construct(array $server = array(), History $history = null, CookieJar $cookieJar = null)
    {
        $this->setServerParameters($server);
        $this->history = $history ?: new History();
        $this->cookieJar = $cookieJar ?: new CookieJar();
    }

and config.neon 

    - Goutte\Client

this exception is raised exception 'Nette\DI\ServiceCreationException' with message 'Class array needed by Symfony\Component\BrowserKit\Client::__construct() not found. Check type hint and 'use' statements.'

this class is just an example, it happens with all array typehints. it started to happen in recent versions of nette

before it worked just fine

**Comment by pavelkouril** [comment]
This is probably a bug introduced either by the refactoring @dg did or the PR I did for 7.0 scalar type hints.

Are you able to locate the exact commit when this has started to happen?

**Comment by JanTvrdik** [comment]
@bazo PHP and Nette version?

**Comment by fprochazka** [comment]
Reproduced in my build https://travis-ci.org/Kdyby/RabbitMq/jobs/79003947

**Comment by bazo** [comment]
@JanTvrdik latest master. php 5.6.10

@pavelkouril no, didn't have much time to play around
