### ISSUE TITLE
Rough start

### ISSUE THREAD

**Issue by olvlvl** [nette/di#86]
Hi guys,

I'm having a rough start with nette/di. I'm trying to replace the PHP parser of ApiGen by nikic's and I'm already stuck with nette/di service definition:

https://github.com/ApiGen/ApiGen/blob/master/src/Parser/DI/ParserExtension.php#L28

I would expect to be able to define the service as follows:

```
$builder->addDefinition($this->prefix('broker'))
            ->setFactory(function() {
                return (new ParserFactory)->create(ParserFactory::PREFER_PHP7)
            });
```

Alas, this throws a `InvalidArgumentException`. I read the following docs, but found nothing involving closures for `addDefinition`, its often a class name and some arguments:

- https://doc.nette.org/en/2.3/dependency-injection
- https://doc.nette.org/en/2.3/di-extensions

Please help :'(

**Comment by hrach** [comment]
Builder helps you to create a php class, which will be stored and loaded in execution time. Therefore it's not allowed to put there a clousure, which cannot be easily serialized into outputted php code. Something like this could work (srr, I'm out of home):
```
$definition->setFactory('ParserFactory::create', [ParserFactory::PREFER_PHP7]);
```

**Comment by olvlvl** [comment]
It does! Thanks <3

**Comment by hrach** [comment]
You may wanna pass a Statement as an argument, since in the current way it pass only the value of the constant, not generate the constant itself.

**Comment by fprochazka** [comment]
@hrach @dg if we create a php parser that can fetch the code inside the closure, we might be able to serialize it to the resulting container. Ofcourse, it cannot contain any variables in `use()`
