### ISSUE TITLE
Inject extension is not called as last extension

### ISSUE THREAD

**Issue by KacerCZ** [nette/di#88]
In `Nette\DI\Compiler::processExtensions()` (https://github.com/nette/di/blob/master/src/DI/Compiler.php#L159) is `InjectExtension` moved to end of list of extension.

If any extension is later added by `ExtensionsExtension`, then new extension is added after `InjectExtension`. This means, that any services added in extension in `beforeCompile()` can't take advantage of `InjectExtension`.

I believe, that line 159 (moving `InjectExtension` to end of extensions) should be after calling `ExtensionsExtension::loadConfiguration()` to line 168.

**Comment by fprochazka** [comment]
@dg nice, IMHO this should be done also for `DecoratorExtension`, which should be added before `InjectExtension`. What do you think?

**Comment by dg** [comment]
I am not sure, tags added via DecoratorExtension should be added soon.
