### ISSUE TITLE
Multiple services from generated factory

### ISSUE THREAD

**Issue by castamir** [nette/di#89]
Is it possible to generate multiple services from a single generated factory?

I've got several similar services with additional dependencies given at runtime (Strategy pattern) and I'd like to avoid writing my own factory class and repeat myself so many times when changing a single dependency as well as i'd like to avoid writing multiple single generated factories (I'm talking about ten up to twenty services / strategies, that means up to 20 factories).

Is this possible? Is it a good idea or not? What do you think?

**Comment by dg** [comment]
Please use forum for discussing.
