### ISSUE TITLE
getByType() does not consider autowired: false

### ISSUE THREAD

**Issue by hrach** [nette/di#90]
Calling getByType() thows an exception multiple definiton of sevice, though, only one of them is set as autowired.

Why not return only the autowired one?

**Comment by JanTvrdik** [comment]
This should work just fine, see https://github.com/nette/di/blob/f205c2cbcb19e361950a11cc88d1e1f4cd95a47d/src/DI/Container.php#L178-L190

**Comment by hrach** [comment]
I saw it and then open the issue. See the count() === 1.

**Comment by hrach** [comment]
Well, it's possible, that some key (such true) in meta points only to autowired services. I had this problem in my app, but I may misinterpret that situation.

**Comment by JanTvrdik** [comment]
The `[TRUE]` should mean "autowired-only"

**Comment by dg** [comment]
Can you provide failing test/code?

**Comment by hrach** [comment]
Yes, I will try to reproduce this or I will close this :) Thanks.

**Comment by hrach** [comment]
seems to be my fail, sorry :)
