### ISSUE TITLE
Broken InjectExtension with removed definition

### ISSUE THREAD

**Issue by MartinSadovy** [nette/di#94]
#71 #72 broke InjectExtension. When [another extension override definition with own definition](https://github.com/Kdyby/Doctrine/blob/master/src/Kdyby/Doctrine/DI/OrmExtension.php#L741), it removes class from $classes, but ->addDefinition does not add new.

certain description (see link):
1) $classes is prepared by https://github.com/nette/di/blob/master/src/DI/Compiler.php#L202
2) OrmExtension override definition https://github.com/Kdyby/Doctrine/blob/master/src/Kdyby/Doctrine/DI/OrmExtension.php#L741 (beforeCompile) - remove $classes https://github.com/nette/di/blob/master/src/DI/ContainerBuilder.php#L81
3) Next extension (InjectExtension) want to service by class in beforeCompile https://github.com/nette/di/blob/master/src/DI/Extensions/InjectExtension.php#L126 (btw. see second param which missing)
4) there is null https://github.com/nette/di/blob/master/src/DI/ContainerBuilder.php#L210

testcase:
```
$builder = new DI\ContainerBuilder;

$builder->addDefinition('one')
	->setClass('stdClass');

$builder->prepareClassList();

$builder->removeDefinition('one');
$builder->addDefinition('one')
	->setClass('stdClass');

Assert::count(1, $builder->findByType('stdClass')); // Failed: Count 0 should be 1
Assert::same('one', $builder->getByType('stdClass')); // Failed: NULL should be 'one'
```

**Comment by fprochazka** [comment]
Is this realted to https://github.com/Kdyby/Doctrine/issues/234 ?

**Comment by enumag** [comment]
@fprochazka The referenced commits are several months old so probably not.

**Comment by MartinSadovy** [comment]
@fprochazka correct, it is.

**Comment by dg** [comment]
You should call `prepareClassList` again.

**Comment by MartinSadovy** [comment]
@dg I know. Testcase is same as ContainerBuilder works, otherwise the testcase will successful.
