### ISSUE TITLE
findByType not work properly

### ISSUE THREAD

**Issue by AntikCz** [nette/di#96]
Example is more than text, so:

**IMy:**
```php

interface IMy {

    /**
     * @return My
     */
    public function create();

}
```

**My:**
```php
class My implements IMyInterface {

}
```

**IMyInterface:**
```php
interface IMyInterface {}
```

**Extension:**
```php
class Extension extends CompilerExtension {

    public function beforeCompiler() {
          $this->getContainerBuilder()->findByType('IMyInterface'); // Cannot find class 'My'
    }

}
```

If I changed IMy to:
```php
class IMy extends IMyInterface { //... }
```

Now can builder find class 'My'

Question: It´s correct behavior?

**Comment by dg** [comment]
And contents of config.neon?

**Comment by AntikCz** [comment]
```yaml
services:
    - IMy
```

I know, that this works:
```yaml
services:
    class: IMy
    factory: My
```

**Comment by enumag** [comment]
The behavior is correct. You're supposed to inject `IMy` and call create to get an instance of `IMyInterface`.

**Comment by AntikCz** [comment]
When I sent the last message, I had changed my mind. Thank you all and sorry for the unnecessary issue.
