### ISSUE TITLE
Strange: Case mismatch on class name error with even stranger fix.

### ISSUE THREAD

**Issue by josefsabl** [nette/di#97]
Today I updated are composer dependencies and our app started to throw this exception:

https://dl.dropboxusercontent.com/u/3215457/exception--2016-02-24--13-59--3ca7ce7b19.html

The solution to fix it was to change the routerFactory like this:

http://screenpresso.com/=qHr2c

**Comment by milo** [comment]
Imho, you should not use leading `\` in use clause.

**Comment by josefsabl** [comment]
I never realized that use usually doesn't use the leading slash. Probably because Netbeans automatically puts it in there automatically. Anyways, thanks for the fix.

**Comment by lookyman** [comment]
Actually, according to PHP documentation, 
> the leading backslash is unnecessary and not recommended, as import names must be fully qualified, and are not processed relative to the current namespace

https://secure.php.net/manual/en/language.namespaces.importing.php
